CREATE TABLE FMS_FILE_METADATA (
  ID          BIGINT PRIMARY KEY    AUTO_INCREMENT,
  SOURCE_NAME VARCHAR(64)  NOT NULL COMMENT '原文件名(有后缀)',
  DEST_NAME   VARCHAR(64)  NOT NULL COMMENT '文件保存到OSS的名称(无后缀)',
  SUFFIX      VARCHAR(64)  NOT NULL COMMENT '文件后缀',
  SIZE        BIGINT       NOT NULL COMMENT '文件大小, 单位是byte',
  CREATED_AT  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '上传时间'
);