CREATE TABLE FMS_BIG_FILE_METADATA (
  ID          BIGINT PRIMARY KEY    AUTO_INCREMENT,
  SOURCE VARCHAR(64)  NOT NULL COMMENT '文件来源(有后缀)',
  SOURCE_NAME VARCHAR(64)  NOT NULL COMMENT '原文件名(有后缀)',
  SUFFIX      VARCHAR(64)  NOT NULL COMMENT '文件后缀',
  CREATED_AT  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '上传时间'
);
ALTER TABLE FMS_BIG_FILE_METADATA ADD UNIQUE (`SOURCE_NAME`);